/*
 * generated by Xtext
 */
package org.cfeditor.cfengine.ui.contentassist

import org.cfeditor.cfengine.ui.contentassist.AbstractCfengineProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class CfengineProposalProvider extends AbstractCfengineProposalProvider {
}
