/*
 * generated by Xtext
 */
package org.cfeditor.cfengine.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCfengineValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.cfeditor.cfengine.cfengine.CfenginePackage.eINSTANCE);
		return result;
	}
}
