/*
* generated by Xtext
*/
package edu.kit.scc.cfeditor.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CfeditorTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
