/*
 * generated by Xtext
 */
package org.cfeditor.cfengine.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.cfeditor.cfengine.ui.internal.CfEditorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CfEditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CfEditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CfEditorActivator.getInstance().getInjector(CfEditorActivator.ORG_CFEDITOR_CFENGINE_CFEDITOR);
	}
	
}
