/*
 * generated by Xtext
 */
package org.cfeditor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CfengineRuntimeModule extends org.cfeditor.AbstractCfengineRuntimeModule {
	/**
	 * Binds the customized value converter.
	 */
	@Override
	public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
		return CfengineTerminalConverters.class;
	}
}
