/*
* generated by Xtext
*/
package org.cfeditor;

import org.cfeditor.CfengineStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CfengineStandaloneSetup extends CfengineStandaloneSetupGenerated{

	public static void doSetup() {
		new CfengineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

