/*
 * generated by Xtext
 */
package org.cfeditor.cfengine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CfengineRuntimeModule extends org.cfeditor.cfengine.AbstractCfengineRuntimeModule {

}
