/**
 * generated by Xtext
 */
package org.cfeditor.ui.contentassist;

import org.cfeditor.ui.contentassist.AbstractCfengineProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CfengineProposalProvider extends AbstractCfengineProposalProvider {
}
