/*
* generated by Xtext
*/
package org.cfeditor.cfengine;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CfengineStandaloneSetup extends CfengineStandaloneSetupGenerated{

	public static void doSetup() {
		new CfengineStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

