/*
 * generated by Xtext
 */
package org.cfeditor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CfEditorRuntimeModule extends org.cfeditor.AbstractCfEditorRuntimeModule {

}
