/*
* generated by Xtext
*/
package org.cfeditor;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CfEditorUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.cfeditor.ui.internal.CfEditorActivator.getInstance().getInjector("org.cfeditor.CfEditor");
	}
	
}
