/*
 * generated by Xtext
 */
package org.cfeditor.cfengine.validation
//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class CfengineValidator extends AbstractCfengineValidator {

//  public static val INVALID_NAME = 'invalidName'

//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character::isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage$Literals::GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
