/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CfeditorUiModule extends
		org.eclipse.xtext.ui.AbstractCfeditorUiModule {
	public CfeditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

//	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
//		return CfeditorHighlightingCalculator.class;
//	}
//
//	public Class<? extends IHighlightingConfiguration> bindSemanticConfig() {
//		return CfeditorHighlightingConfiguration.class;
//	}
	
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return org.eclipse.xtext.ui.wizard.CfeditorNewProjectCreator.class;
	}
	
	

}
