/*
* generated by Xtext
*/
package org.cfeditor.cfengine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CfengineUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.cfeditor.cfengine.ui.internal.CfengineActivator.getInstance().getInjector("org.cfeditor.cfengine.Cfengine");
	}
	
}
