/*
 * generated by Xtext
 */
package edu.kit.scc.cfeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

import edu.kit.scc.cfeditor.ui.highlighting.CfeditorHighlightingCalculator;
import edu.kit.scc.cfeditor.ui.highlighting.CfeditorHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author Andreas Bender
 * 
 */
public class CfeditorUiModule extends edu.kit.scc.cfeditor.ui.AbstractCfeditorUiModule {

	/**
	 * Constructor for the ui module.
	 * 
	 * @param plugin
	 */
	public CfeditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return CfeditorHighlightingCalculator.class;
	}

	public Class<? extends IHighlightingConfiguration> bindSemanticConfig() {
		return CfeditorHighlightingConfiguration.class;
	}

	/**
	 * Declares the new Cfeditor project creator class.
	 */
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return edu.kit.scc.cfeditor.ui.wizard.CfeditorNewProjectCreator.class;
	}

}
