/*
 * generated by Xtext
 */
package edu.kit.scc.cfeditor;

import edu.kit.scc.cfeditor.parser.conversion.CfTerminalConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 * 
 * @author Andreas Bender
 * 
 */
public class CfeditorRuntimeModule extends org.eclipse.xtext.AbstractCfeditorRuntimeModule {

	/**
	 * Binds the customized value converter.
	 */
	@Override
	public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
		return CfTerminalConverters.class;
	}

}
