/*
* generated by Xtext
*/
package edu.kit.scc.cfeditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CfeditorAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("edu/kit/scc/cfeditor/parser/antlr/internal/InternalCfeditor.tokens");
	}
}
