/*
 * generated by Xtext
 */
package org.cfeditor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.cfeditor.ui.internal.CfengineActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CfengineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CfengineActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CfengineActivator.getInstance().getInjector(CfengineActivator.ORG_CFEDITOR_CFENGINE);
	}
	
}
